name: Main Workflow
on:
  push:
    branches:
      - test-api-gateway
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: api-gateway/test.js
        env:
          HOSTNAME: ${{ vars.HOSTNAME }}
          AUTHORIZATION: ${{ vars.AUTHORIZATION }}
          X_API_KEY: ${{ vars.X_API_KEY }}